version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync build s3://shenkproperties.com
      - aws cloudfront create-invalidation --paths /index.html --distribution-id E1VRJ6G74GL3AO
artifacts:
  files:
    - 'build/*'

